### ISSUE TITLE
Integration with Gollum

### ISSUE THREAD

**Issue by meddle0x53** [bootstraponline-archive/livepreview_wysi#1]
Hi, sorry that I'm writing here, but I'm trying to have such an editor in our Gollum wiki, I like yours a lot but I don't know how to integrate it our wiki. Is it possible at all?
If it is could you show me or write a gist for it, It will be of great help for me.

**Comment by bootstraponline** [comment]
closing issue as this project was discontinued in 2012. gollum has an integrated editor now.
